Repository georchestra/mapstore2-georchestra, pull requests merged in 2022-01, with the labels that each got.

#452 Fix streetview API key issue
  api.html
  apiTemplate.html
  embedded.html
  embeddedTemplate.html
  index.html
  indexTemplate.html
Labels: Priority: High, Contract #3

#466 backport #464 on 2021.02.xx (fixes #463)
  web/pom.xml
Labels: Backport

#475 Add entry point in react router for map created by context
  js/app.jsx
Labels: Contract #3
