Repository georchestra/mapstore2-georchestra, pull requests merged in 2022-02, with the labels that each got.

#488 #483 Proper configuration for embedded geostories and dashboards.
  dashboard-embedded-template.html
  dashboard-embedded.html
  geostory-embedded-template.html
  geostory-embedded.html
  js/dashboardEmbedded.jsx
  js/geostoryEmbedded.jsx
  prod-webpack.config.js
  webpack.config.js
Labels: bug, Priority: Medium, Contract #3

#490 Update mapstore.yml
  .github/workflows/mapstore.yml
Labels: enhancement, Priority: High, Contract #3

#491 [Backport 2021.02.xx] Proper configuration for embedded geostories and dashboards. (#483)
  dashboard-embedded-template.html
  dashboard-embedded.html
  geostory-embedded-template.html
  geostory-embedded.html
  js/dashboardEmbedded.jsx
  js/geostoryEmbedded.jsx
  prod-webpack.config.js
  webpack.config.js
Labels: bug, investigation, User feedback, Priority: Medium, Backport, Contract #3

#492 Replacing dependencies with list from upstream
  package.json
Labels: enhancement, Priority: High, Contract #3

#493 Update mapstore.yml (#490)
  .github/workflows/mapstore.yml
Labels: Backport, Contract #3
